### PR TITLE
Fix: VTK-writer enables 3D data to be saved.

### PR DESCRIPTION
**Pull request by McBs**
Hey,
the current VTK-writer does not enable 3D data to be saved. The reason is that the tensor of 3D data is extended by a fourth dimension which leads to an error caused by the 'pyevtk' library.
This is, why the extension has to be prevented. First I tried following syntax, but the line becomes too long in terms of characters.

`self.point_dict["p"] = self.lattice.convert_to_numpy(p[0, ..., None]) if self.lattice.D == 2: else self.lattice.convert_to_numpy(p[0, ...])`

### CODE REVIEW

**Comment by Olllom** [comment]
I agree that the `if` ... `else` block is a better solution here. Thank you.
Why is the BGKSmagorinsky code also in here? Was it meant to be or did this happen by accident?
Btw. you can in most cases break python lines by adding parentheses like this
```
i = ( 1 + 2 + 3
       + 4 + 5 + 6)
```
or 
```
i = ("something really complicated" 
       if True
       else "something else"
)

**Comment by McBs** [comment]
Yes this was an accident. The BGKSmagorinsky code is taken from [Dominik Wilde](https://github.com/dominikwilde), who hopefully is going to merge this in a few days...
Thanks for the hint.

**Comment by Olllom** [comment]
could you remove the Smagorinski code from the PR, please?

**Comment by Olllom** [comment]
Something like 
```
git checkout master lettuce/collision.py
git add lettuce/collision.py
git commit 
```

**Comment by Olllom** [comment]
Note that `SmagorinskyCollision` is already in the current master, under a slightly different name though.

**Comment by Olllom** [comment]
thanks! will merge after tests pass.

**Pull request merged**
