### PR TITLE
Shear layer

### PR DESCRIPTION
**Pull request by MartinKliemank**
Hi, I am a student assistant working with DominikWilde. I did a thing:

Added Doublyperiodic shear layer as new test case in a new file, also added new file to __init__.py

### CODE REVIEW

**Comment by Olllom** [comment]
Hi @MartinKliemank,

welcome on board!
This looks very good. Is there any test that you could add to `tests/test_flows.py` to make me believe that everything is alright here? 

@dominikwilde Can you review this, please?

**Comment by dominikwilde** [comment]
The code of the shear layer is good.

Only the additions in tests/test_flows.py are missing.

**Comment by MartinKliemank** [comment]
@Olllom Thank you!
I have (hopefully) added the new flow to test_flows.py, it seems to run the test, though it returns: 
SKIPPED [ 33%]
Skipped: Half precision is not precise enough ;-)

Does that mean I need to change something or is that a normal behavior?

**Comment by Olllom** [comment]
That's no problem at all. I'll get rid of this in a separate PR.
Thanks for this addition.

**Pull request merged**
