### PR TITLE
fix units in reporters

### PR DESCRIPTION
**Pull request by Olllom**
Everything that is reported should be in physical units!

@McBs 
please check if this looks correct.

@dominikwilde 
Please have a look, since it may break some of your stuff with Alex downstream.

### CODE REVIEW

**Comment by Olllom** [comment]
btw. i deleted the mass reporter

**Comment by McBs** [comment]
I think, that the integral of the enstrophy reporter is incorrect. There is missing something like:
enstrophy = self.flow.units.convert_length_to_pu(1.0) ** self.lattice.D * vorticity

**Comment by Olllom** [comment]
Yes that sounds right

**Comment by McBs** [comment]
Seems the scale is right.
Fixed the bug in the Enstophy and took Brachet as reference
dissipation

**Comment by Olllom** [comment]
This looks quite good. What resolution is this? When you run at a higher resolution, the blue and red curves should move closer together due to better resolution of smaller vortices. Can you confirm?

**Comment by McBs** [comment]
yes, I can confirm that. The resolution was 100. Here are 2 additional simulations: 
tgv3d_dissipation_Re200_Res150
tgv3d_dissipation_Re1600_Res200

**Comment by Olllom** [comment]
OK, looks great! Thanks!

@dominikwilde @McBs
Please check if we need any more changes to this branch before I need it or if there is anything that you don’t like/breaks any of your code downstream.

@McBs
Were these graphs made with or without the dx**self.lattice.D in the reporter?

**Comment by McBs** [comment]
@Olllom 
Both graphs were calculated with dx**self.lattice.D within the reporter ;-)

**Comment by Olllom** [comment]
> @Olllom
> Both graphs were calculated with dx**self.lattice.D within the reporter ;-)

Alright, fixed

**Comment by Olllom** [comment]
@McBs Btw. I think the discrepancy for the 200 resolution that you are seeing here is due to the low-order gradient in the vorticity that we talked about last week. I am pretty sure that the enstrophy at this resolution and Reynolds number should be quite accurate for the TGV. @dominikwilde it might be worthwhile to code up a higher order (e.g. 4th order) finite difference instead of just using np.gradient (which is 2nd order). Just saying, if we are to put enstrophy results in any paper, 2nd order is probably indefensible (in natrium, we don't have that issue since the vorticity is computed through analytic gradients of high-order ansatz functions).

**Comment by dominikwilde** [comment]
Alright, this is an important topic. I underestimated the role of the gradients' order so far. @McBs agreed to check how to implement the high-order derivatives in PyTorch.

Apart from that all changes look good.

**Comment by Olllom** [comment]
cool. Will merge this then.

**Pull request merged**
