### PR TITLE
Report zeroth step

### PR DESCRIPTION
**Pull request by Olllom**
In many cases we want to actually have access to the output at t=0.
Therefore, I moved the reporting to the beginning of the simulation step.

@dominikwilde @McBs @MartinKliemank 
Please tell me, if you don't agree with this.

### CODE REVIEW

**Comment by McBs** [comment]
👍🏽 - perfect - just like this.

**Comment by dominikwilde** [comment]
The most comprehensive solution would be to add another round of reporting just after the loop - otherwise the final time step does not have any meaning. I am aware of the overhead.

**Comment by Olllom** [comment]
> The most comprehensive solution would be to add another round of reporting just after the loop - otherwise the final time step does not have any meaning. I am aware of the overhead.

ok

**Comment by dominikwilde** [comment]
Marvellous :1st_place_medal:

**Pull request merged**
